profiles:
- deviceName: "mqtt-test-device"
  manufacturer: "Dell"
  model: "MQTT-3"
  description: "Test device profile"
  deviceResources:
  - name: randfloat32
    description: "random 32 bit float"
    properties:
      valueType: "Float32"
      readWrite: "RW"
      defaultValue: "0.00"
      minimum: 0
      maximum: 100
  - name: randfloat64
    description: "random 64 bit float"
    properties:
      valueType: "Float64"
      readWrite: "RW"
      defaultValue: "0.00"
      minimum: 0
      maximum: 100
  - name: ping
    description: "device awake"
    properties:
      valueType: "String"
      readWrite: "R"
      defaultValue: "oops"
  - name: message
    description: "device notification message"
    properties:
      valueType: "String"
      readWrite: "RW"
  - name: json
    description: "JSON message"
    properties:
      valueType: "Object"
      readWrite: "RW"
      mediaType: "application/json"
  deviceCommands:
  - name: allValues
    readWrite: "RW"
    resourceOperations:
      - { deviceResource: "randfloat32" }
      - { deviceResource: "randfloat64" }
      - { deviceResource: "message" }
