// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/skeeey/device-addon/pkg/apis/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DeviceDataModelLister helps list DeviceDataModels.
// All objects returned here must be treated as read-only.
type DeviceDataModelLister interface {
	// List lists all DeviceDataModels in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.DeviceDataModel, err error)
	// Get retrieves the DeviceDataModel from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.DeviceDataModel, error)
	DeviceDataModelListerExpansion
}

// deviceDataModelLister implements the DeviceDataModelLister interface.
type deviceDataModelLister struct {
	indexer cache.Indexer
}

// NewDeviceDataModelLister returns a new DeviceDataModelLister.
func NewDeviceDataModelLister(indexer cache.Indexer) DeviceDataModelLister {
	return &deviceDataModelLister{indexer: indexer}
}

// List lists all DeviceDataModels in the indexer.
func (s *deviceDataModelLister) List(selector labels.Selector) (ret []*v1alpha1.DeviceDataModel, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.DeviceDataModel))
	})
	return ret, err
}

// Get retrieves the DeviceDataModel from the index for a given name.
func (s *deviceDataModelLister) Get(name string) (*v1alpha1.DeviceDataModel, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("devicedatamodel"), name)
	}
	return obj.(*v1alpha1.DeviceDataModel), nil
}
