apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-addon-agent
  namespace: {{ .AddonInstallNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      addon-agent: device-addon-agent
  template:
    metadata:
      labels:
        addon-agent: device-addon-agent
    spec:
      serviceAccount: device-addon-agent-sa
      containers:
        - name: device-addon-agent
          image: quay.io/skeeey/device-addon:latest
          imagePullPolicy: Always
          args:
          - "/device-addon"
          - "agent"
          - --cluster-name={{ .ClusterName }}
          - --hub-kubeconfig=/etc/hub/kubeconfig
          volumeMounts:
            - name: hub-kubeconfig
              mountPath: /etc/hub/
              readOnly: true
      volumes:
        - name: hub-kubeconfig
          secret:
            secretName: device-addon-hub-kubeconfig
