apiVersion: v1
kind: Service
metadata:
  name: deviceaddon-messagebus-mqtt
  namespace:  {{ .AddonInstallNamespace }}
  labels:
    addon-agent: device-addon-agent
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: default
      protocol: TCP
      name: default
  selector:
    addon-agent: device-addon-agent