apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
    spec:
      serviceAccountName: mosquitto
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: default
              containerPort: 1883
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: default
          readinessProbe:
            tcpSocket:
              port: default
          volumeMounts:
            - name: configmap
              mountPath: /mosquitto/config
      volumes:
        - name: configmap
          configMap:
            name: mosquitto
