apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: default
      protocol: TCP
      name: default
  selector:
    app.kubernetes.io/name: mosquitto