apiVersion: edge.open-cluster-management.io/v1alpha1
kind: DeviceDataModel
metadata:
  name: temperature-sensor
spec:
  attributes:
  - name: monitorring-interval
    description: counter status
    type: int
    unit: "seconds"
  - name: temperature
    description: counter status
    type: int
    unit: "Celsius"
