apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-addon-manager
  namespace: device-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      open-cluster-management.io/addon: device-addon
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: device-addon
    spec:
      serviceAccount: device-addon-sa
      containers:
        - name: manager
          image: quay.io/skeeey/device-addon:latest
          imagePullPolicy: Always
          args:
          - "/device-addon"
          - "manager"
