
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds/edge.open-cluster-management.io_devicedatamodels.yaml
- crds/edge.open-cluster-management.io_devices.yaml
- clustermanagementaddon.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- namespace.yaml
- serviceaccount.yaml
- deployment.yaml

generatorOptions:
  disableNameSuffixHash: true
