// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/skeeey/device-addon/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Devices returns a DeviceInformer.
	Devices() DeviceInformer
	// DeviceDataModels returns a DeviceDataModelInformer.
	DeviceDataModels() DeviceDataModelInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Devices returns a DeviceInformer.
func (v *version) Devices() DeviceInformer {
	return &deviceInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DeviceDataModels returns a DeviceDataModelInformer.
func (v *version) DeviceDataModels() DeviceDataModelInformer {
	return &deviceDataModelInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
